"""meals table2

Revision ID: 745b1c5e5397
Revises: 
Create Date: 2019-06-18 21:16:11.138809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '745b1c5e5397'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meal', sa.Column('image', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meal', 'image')
    # ### end Alembic commands ###
